export const CONFIG = {
    ACTOR_HIDDEN_LAYER_LENGTHS: [32, 32],
    CRITIC_HIDDEN_LAYER_LENGTHS: [32, 32],
    GAME_STATE_SIZE: 30,
    ACTION_SIZE: 6,
    ACTOR_LEARNING_RATE: 0.001,
    CRITIC_LEARNING_RATE: 0.001,
    BATCH_SIZE: 64,
    DISCOUNT_FACTOR: 0.96,
    ENTROPY_COEFFICIENT: 0.01,
    
    PLAYER_ONE_ID: 200,
    PLAYER_TWO_ID: 201,
    REWARD_NORMALIZATION: 1/100,
    POSITION_NORMALIZATION: 1/100,
    VELOCITY_NORMALIZATION: 1/10,
};